import json

notebook_content = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": [
        {
            "cell_type": "markdown",
            "id": "cell-1",
            "metadata": {},
            "source": ["# SHL Grammar Scoring Engine - Self-Contained High-Performance Model"]
        },
        {
            "cell_type": "code",
            "id": "cell-2",
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "INPUT_DIR = None\n",
                "search_roots = ['/kaggle/input', '.', r'C:\\Users\\HP\\Downloads']\n",
                "for root_dir in search_roots:\n",
                "    if os.path.exists(root_dir):\n",
                "        for root, dirs, files in os.walk(root_dir):\n",
                "            if 'train.csv' in files:\n",
                "                INPUT_DIR = os.path.abspath(root)\n",
                "                break\n",
                "    if INPUT_DIR is not None:\n",
                "        break\n",
                "\n",
                "if INPUT_DIR is None:\n",
                "    raise FileNotFoundError('train.csv could not be found')\n",
                "\n",
                "AUDIO_DIR = os.path.join(INPUT_DIR, 'train') if os.path.exists(os.path.join(INPUT_DIR, 'train')) else os.path.join(INPUT_DIR, 'audios_train')\n",
                "TEST_AUDIO = os.path.join(INPUT_DIR, 'test') if os.path.exists(os.path.join(INPUT_DIR, 'test')) else os.path.join(INPUT_DIR, 'audios_test')\n",
                "TRAIN_CSV = os.path.join(INPUT_DIR, 'train.csv')\n",
                "TEST_CSV = os.path.join(INPUT_DIR, 'test.csv')\n",
                "SAMPLE_SUB_CSV = os.path.join(INPUT_DIR, 'sample_submission.csv')\n",
                "OUTPUT_DIR = '/kaggle/working' if os.path.exists('/kaggle') else os.path.join(INPUT_DIR, 'output')\n",
                "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
                "\n",
                "SEED = 42\n",
                "np.random.seed(SEED)\n",
                "print('Input:', INPUT_DIR)\n",
                "print('Output:', OUTPUT_DIR)"
            ]
        },
        {
            "cell_type": "code",
            "id": "cell-3",
            "metadata": {},
            "outputs": [],
            "source": [
                "import librosa\n",
                "from tqdm.auto import tqdm\n",
                "\n",
                "train_df = pd.read_csv(TRAIN_CSV)\n",
                "test_df = pd.read_csv(TEST_CSV)\n",
                "\n",
                "def extract_acoustic_features(audio_path, sr=16000):\n",
                "    try:\n",
                "        y, sr = librosa.load(audio_path, sr=sr, mono=True, duration=45.0)\n",
                "    except Exception:\n",
                "        return None\n",
                "    feats = {}\n",
                "    dur = max(len(y) / sr, 1.0)\n",
                "    feats['duration'] = dur\n",
                "    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=26)\n",
                "    for i, c in enumerate(mfcc):\n",
                "        feats[f'mfcc_{i}_mean'] = float(np.mean(c))\n",
                "        feats[f'mfcc_{i}_std'] = float(np.std(c))\n",
                "        feats[f'mfcc_{i}_max'] = float(np.max(c))\n",
                "        feats[f'mfcc_{i}_min'] = float(np.min(c))\n",
                "    d_mfcc = librosa.feature.delta(mfcc)\n",
                "    for i, c in enumerate(d_mfcc):\n",
                "        feats[f'd_mfcc_{i}_mean'] = float(np.mean(c))\n",
                "        feats[f'd_mfcc_{i}_std'] = float(np.std(c))\n",
                "    sc = librosa.feature.spectral_centroid(y=y, sr=sr)[0]\n",
                "    sb = librosa.feature.spectral_bandwidth(y=y, sr=sr)[0]\n",
                "    sr_roll = librosa.feature.spectral_rolloff(y=y, sr=sr)[0]\n",
                "    sf = librosa.feature.spectral_flatness(y=y)[0]\n",
                "    for name, arr in [('spec_cent', sc), ('spec_bw', sb), ('spec_roll', sr_roll), ('spec_flat', sf)]:\n",
                "        feats[f'{name}_mean'] = float(np.mean(arr))\n",
                "        feats[f'{name}_std'] = float(np.std(arr))\n",
                "    rms = librosa.feature.rms(y=y)[0]\n",
                "    feats['rms_mean'] = float(np.mean(rms))\n",
                "    feats['rms_std'] = float(np.std(rms))\n",
                "    feats['rms_max'] = float(np.max(rms))\n",
                "    feats['rms_energy'] = float(np.sum(rms**2) / dur)\n",
                "    zcr = librosa.feature.zero_crossing_rate(y)[0]\n",
                "    feats['zcr_mean'] = float(np.mean(zcr))\n",
                "    feats['zcr_std'] = float(np.std(zcr))\n",
                "    chroma = librosa.feature.chroma_stft(y=y, sr=sr)\n",
                "    for i, ch in enumerate(chroma):\n",
                "        feats[f'chroma_{i}_mean'] = float(np.mean(ch))\n",
                "        feats[f'chroma_{i}_std'] = float(np.std(ch))\n",
                "    try:\n",
                "        intervals = librosa.effects.split(y, top_db=25)\n",
                "        active_len = sum((end - start) for start, end in intervals) / sr\n",
                "        feats['active_speech_ratio'] = float(active_len / dur)\n",
                "        feats['pause_ratio'] = float(1.0 - (active_len / dur))\n",
                "        feats['pause_count'] = float(len(intervals))\n",
                "        feats['pause_rate'] = float(len(intervals) / dur)\n",
                "    except Exception:\n",
                "        feats['active_speech_ratio'] = 1.0\n",
                "        feats['pause_ratio'] = 0.0\n",
                "        feats['pause_count'] = 0.0\n",
                "        feats['pause_rate'] = 0.0\n",
                "    onset_env = librosa.onset.onset_strength(y=y, sr=sr)\n",
                "    feats['onset_mean'] = float(np.mean(onset_env))\n",
                "    feats['onset_std'] = float(np.std(onset_env))\n",
                "    tempo, _ = librosa.beat.beat_track(y=y, sr=sr)\n",
                "    feats['tempo'] = float(tempo) if np.isscalar(tempo) else float(tempo[0])\n",
                "    return feats\n",
                "\n",
                "train_cache = os.path.join(OUTPUT_DIR, 'train_features.csv')\n",
                "test_cache = os.path.join(OUTPUT_DIR, 'test_features.csv')\n",
                "\n",
                "if os.path.exists(train_cache):\n",
                "    train_df_feats = pd.read_csv(train_cache)\n",
                "else:\n",
                "    print('Extracting train audio features...')\n",
                "    recs = []\n",
                "    for _, r in tqdm(train_df.iterrows(), total=len(train_df)):\n",
                "        f = extract_acoustic_features(os.path.join(AUDIO_DIR, r['filename']))\n",
                "        if f is not None:\n",
                "            f['filename'] = r['filename']\n",
                "            f['label'] = r['label']\n",
                "            recs.append(f)\n",
                "    train_df_feats = pd.DataFrame(recs)\n",
                "    train_df_feats.to_csv(train_cache, index=False)\n",
                "\n",
                "if os.path.exists(test_cache):\n",
                "    test_df_feats = pd.read_csv(test_cache)\n",
                "else:\n",
                "    print('Extracting test audio features...')\n",
                "    recs = []\n",
                "    for _, r in tqdm(test_df.iterrows(), total=len(test_df)):\n",
                "        f = extract_acoustic_features(os.path.join(TEST_AUDIO, r['filename']))\n",
                "        if f is not None:\n",
                "            f['filename'] = r['filename']\n",
                "            recs.append(f)\n",
                "    test_df_feats = pd.DataFrame(recs)\n",
                "    test_df_feats.to_csv(test_cache, index=False)\n",
                "\n",
                "print('Train features shape:', train_df_feats.shape)\n",
                "print('Test features shape:', test_df_feats.shape)"
            ]
        },
        {
            "cell_type": "code",
            "id": "cell-4",
            "metadata": {},
            "outputs": [],
            "source": [
                "from sklearn.model_selection import StratifiedKFold\n",
                "from sklearn.preprocessing import RobustScaler\n",
                "from sklearn.linear_model import Ridge, ElasticNet\n",
                "from sklearn.metrics import mean_squared_error\n",
                "from scipy.stats import pearsonr\n",
                "from scipy.optimize import minimize\n",
                "import xgboost as xgb\n",
                "import lightgbm as lgb\n",
                "\n",
                "drop_cols = ['filename', 'label']\n",
                "feature_cols = [c for c in train_df_feats.columns if c not in drop_cols and c in test_df_feats.columns]\n",
                "\n",
                "train_clean = train_df_feats.copy().reset_index(drop=True)\n",
                "\n",
                "X_train = train_clean[feature_cols].fillna(0).replace([np.inf, -np.inf], 0).values\n",
                "y_train = train_clean['label'].values\n",
                "X_test = test_df_feats[feature_cols].fillna(0).replace([np.inf, -np.inf], 0).values\n",
                "\n",
                "scaler = RobustScaler()\n",
                "X_train_s = scaler.fit_transform(X_train)\n",
                "X_test_s = scaler.transform(X_test)\n",
                "\n",
                "FOLDS = 5\n",
                "y_binned = pd.qcut(y_train, q=FOLDS, labels=False, duplicates='drop')\n",
                "skf = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=SEED)\n",
                "\n",
                "lgb_model = lgb.LGBMRegressor(\n",
                "    n_estimators=350,\n",
                "    learning_rate=0.03,\n",
                "    num_leaves=18,\n",
                "    min_child_samples=15,\n",
                "    subsample=0.8,\n",
                "    colsample_bytree=0.6,\n",
                "    reg_alpha=0.5,\n",
                "    reg_lambda=2.0,\n",
                "    random_state=SEED,\n",
                "    n_jobs=-1,\n",
                "    verbose=-1\n",
                ")\n",
                "\n",
                "xgb_model = xgb.XGBRegressor(\n",
                "    n_estimators=350,\n",
                "    learning_rate=0.03,\n",
                "    max_depth=4,\n",
                "    min_child_weight=3,\n",
                "    subsample=0.8,\n",
                "    colsample_bytree=0.6,\n",
                "    reg_alpha=0.5,\n",
                "    reg_lambda=2.0,\n",
                "    random_state=SEED,\n",
                "    n_jobs=-1,\n",
                "    verbosity=0\n",
                ")\n",
                "\n",
                "ridge_model = Ridge(alpha=30.0)\n",
                "enet_model = ElasticNet(alpha=0.05, l1_ratio=0.5, random_state=SEED)\n",
                "\n",
                "def run_cv(model, X_tr, y_tr, X_te):\n",
                "    oof = np.zeros(len(y_tr))\n",
                "    preds = np.zeros(len(X_te))\n",
                "    for tr_idx, va_idx in skf.split(X_tr, y_binned):\n",
                "        model.fit(X_tr[tr_idx], y_tr[tr_idx])\n",
                "        oof[va_idx] = model.predict(X_tr[va_idx])\n",
                "        preds += model.predict(X_te) / FOLDS\n",
                "    return oof, preds\n",
                "\n",
                "lgb_oof, lgb_test = run_cv(lgb_model, X_train_s, y_train, X_test_s)\n",
                "xgb_oof, xgb_test = run_cv(xgb_model, X_train_s, y_train, X_test_s)\n",
                "ridge_oof, ridge_test = run_cv(ridge_model, X_train_s, y_train, X_test_s)\n",
                "enet_oof, enet_test = run_cv(enet_model, X_train_s, y_train, X_test_s)\n",
                "\n",
                "print('LGB RMSE:', round(float(np.sqrt(mean_squared_error(y_train, lgb_oof))), 4))\n",
                "print('XGB RMSE:', round(float(np.sqrt(mean_squared_error(y_train, xgb_oof))), 4))\n",
                "print('Ridge RMSE:', round(float(np.sqrt(mean_squared_error(y_train, ridge_oof))), 4))\n",
                "print('ElasticNet RMSE:', round(float(np.sqrt(mean_squared_error(y_train, enet_oof))), 4))\n",
                "\n",
                "def objective(w):\n",
                "    pred = w[0]*lgb_oof + w[1]*xgb_oof + w[2]*ridge_oof + w[3]*enet_oof\n",
                "    return np.sqrt(mean_squared_error(y_train, pred))\n",
                "\n",
                "opt = minimize(objective, [0.35, 0.35, 0.15, 0.15], bounds=[(0,1)]*4)\n",
                "weights = opt.x / np.sum(opt.x)\n",
                "final_oof = weights[0]*lgb_oof + weights[1]*xgb_oof + weights[2]*ridge_oof + weights[3]*enet_oof\n",
                "final_test = weights[0]*lgb_test + weights[1]*xgb_test + weights[2]*ridge_test + weights[3]*enet_test\n",
                "\n",
                "final_rmse = np.sqrt(mean_squared_error(y_train, final_oof))\n",
                "final_pearson, _ = pearsonr(y_train, final_oof)\n",
                "print('Ensemble CV RMSE:', round(float(final_rmse), 4))\n",
                "print('Ensemble CV Pearson:', round(float(final_pearson), 4))"
            ]
        },
        {
            "cell_type": "code",
            "id": "cell-5",
            "metadata": {},
            "outputs": [],
            "source": [
                "clipped_test = np.clip(final_test, 0.0, 5.0)\n",
                "sub_df = pd.DataFrame({\n",
                "    'filename': test_df_feats['filename'].values,\n",
                "    'label': clipped_test\n",
                "})\n",
                "\n",
                "all_expected = test_df['filename'].tolist()\n",
                "sub_df = sub_df.set_index('filename').reindex(all_expected).reset_index()\n",
                "sub_df.columns = ['filename', 'label']\n",
                "\n",
                "sub_path = os.path.join(OUTPUT_DIR, 'submission.csv')\n",
                "sub_df.to_csv(sub_path, index=False)\n",
                "print('Saved submission to:', sub_path)\n",
                "print('Shape:', sub_df.shape)\n",
                "print(sub_df.head(10))"
            ]
        }
    ]
}

with open(r'C:\Users\HP\Downloads\shl-hiring-assessment-2026\shl_grammar_scoring_engine.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1)

with open(r'C:\Users\HP\.gemini\antigravity-ide\brain\ba75e709-6242-4f9f-b586-b4f7bb5338c6\shl_grammar_scoring_engine.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1)

print('Updated self-contained notebook created successfully!')
